# Generated by Django 4.2.10 on 2024-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_donation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
