# Generated by Django 4.2.10 on 2024-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_userrecyclingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecyclingmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recycling_images/'),
        ),
    ]
