# Generated by Django 4.2.10 on 2024-04-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_recyclingmaterial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingmaterial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recyclingmaterial',
            name='point_value',
            field=models.IntegerField(),
        ),
    ]
